development:
  host: localhost
  database: pulsus_development

test:
  host: localhost
  database: pulsus_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>